CUDA_VISIBLE_DEVICES=1,2,3 python train_query_mutator.py \
  --target-model llava:latest \
  --judge-model deepseek-r1:14b \
  --use-llm-judge \
  --dataset dataset/prompts_harmful_responses_train.csv \
  --frac-samples 1.0 \
  --num-processes 3 \
  --num-env-steps 10000 \
  --num-steps 32 \
  --lr 0.001 \
  --entropy-coef 0.05 \
  --ppo-epoch 4 \
  --num-mini-batch 4 \
  --batch-size 128 \
  --save-interval 500